# Generated by Django 3.0.6 on 2020-06-01 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0005_auto_20200601_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 15, 22, 20, 519080)),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
