# Generated by Django 3.0.6 on 2020-06-01 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0015_auto_20200601_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 15, 45, 28, 271658)),
        ),
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 15, 45, 28, 267663)),
        ),
    ]
