# Generated by Django 3.0.6 on 2020-06-01 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0018_auto_20200601_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(default=1, verbose_name='djangodbmodelsfieldscharfield'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 27, 2, 246429)),
        ),
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 27, 2, 246429)),
        ),
    ]
