# Generated by Django 3.0.6 on 2020-06-01 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0020_auto_20200601_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 34, 42, 855613)),
        ),
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 22, 34, 42, 854006)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
