# Generated by Django 3.0.6 on 2020-06-02 13:43

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('toto', '0021_auto_20200601_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 19, 13, 41, 317073)),
        ),
        migrations.AlterField(
            model_name='question',
            name='datePublished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 19, 13, 41, 317073)),
        ),
    ]
